---
title: "Applying Machine Learning to your Capstone"
author: "Tarji Kinsey"
date: "8/15/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Capstone Project Problem: 
Clark Atlanta University School of Business would like to increase enrollment. We believe identifying factors within the student enrollment data will allow us to predict undergraduate and graduate enrollment for the upcoming Fall 2019 term.

## How do you frame your main question as a machine learning problem? Is it a supervised or unsupervised problem? If it is supervised, is it a regression or a classification? Which machine learning technique will you use?
Main Question: What meaningful patterns within the dataset (using the registration behavior) can be discovered to aid in predicting undergraduate and graduate enrollment for the upcoming Fall 2019 term?

The machine learning technique, Linear Regression, will help determine the relationship between the average number of times a student actually registered (“PERCENTAGE”) and the final registration opportunity during the registration process (“ROUND_4”). 

The machine learning problem is a supervised problem. 

## What are the main features (also called independent variables or predictors) that you'll use?
The main independent variables or predictors that will be used are the registration behavior data (“ROUND_1”, “ROUND_2”, “ROUND_3”, “ROUND_4”, and “PERCENTAGE”) within the dataset.

## How will you evaluate the success of your machine learning technique? What metric will you use?
A Test and Train evaluation will be used to evaluate the success of the machine learning technique. Using the cleaned dataset (enroll_capstone), I will select a test set (“test_x” and test_y) and a training set (train_x and train_y). A random split of data (66% for training, 34% for testing) will be selected from the dataset. I will perform analysis on each subset (training set), and then validate the analysis on the other subset (testing set).
